openapi: 3.0.0
info:
  version: 0.0.1
  title: Kross IAM Administrate API
  description: Manipulate Kross IAM internal structure
  license:
    name: GPL-3.0
    url: 'https://www.gnu.org/licenses/gpl-3.0.html'
  contact:
    name: '@krossdev'
    email: krossdevelop@gmail.com
    url: 'https://github.com/krossdev'

paths:
  /projects/:
    get:
      description: List all projects
      responses:
        '200':
          description: Successful response
          content:
            application/json:
              schema:
                type: object
                properties:
                  action:
                    type: string
    post:
      description: Add new project
      responses:
        '200':
          description: Successful response
          content:
            application/json:
              schema:
                type: object
                properties:
                  action:
                    type: string
# servers:
#   - url: 'http://localhost'
#     description: DEV
